project:
  output-dir: docs
  render:
    - practicals/practical1.qmd
    - practicals/practical2.qmd
    - practicals/regression.qmd
    - practicals/multiplePredictors.qmd
    - practicals/moderation.qmd
    - practicals/mediation.qmd
    - practicals/factorAnalysis.qmd
    - practicals/exam2425.qmd
    
