project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R for Clinical Psychology"
  author: "Christopher J Wilson"
  date: "12/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - working_with_data.qmd
    - descriptive_stats.qmd
    - power_effectSize.qmd
    - basic_tests.qmd
    - correlation.qmd
    - regression.qmd
    - multipleRegression.qmd
    - moderation.qmd
    - ggplot.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

